FROM postgres:latest

# Set environment variables for PostgreSQL
# These can be overridden when running the container
ENV POSTGRES_USER=username
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=db

# Expose the default PostgreSQL port
EXPOSE 5432
